title = "nickmonad"
author = "Nick Miller"
base_url = "https://nickmonad.blog"
compile_sass = false
generate_feeds = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
bottom_footnotes = true
external_links_target_blank = true
highlight_code = true
